import type Category from "@/types/Category";
import type Product from "@/types/Product";

interface State {
  all: Array<Product>,
  categories: Array<Category>
}

const state = () => ({
  all: [
    {
      id: 1,
      nameEN: 'Milk',
      nameRU: 'Молоко',
      nameDE: 'Milch',
      groupId: 1,
    },
    {
      id: 2,
      nameEN: 'Cheese',
      nameRU: 'Сыр',
      nameDE: 'Käse',
      groupId: 1,
    },
    {
      id: 3,
      nameEN: 'Eggs',
      nameRU: 'Яйца',
      nameDE: 'Eier',
      groupId: 1,
    },
    {
      id: 4,
      nameEN: 'Yogurt',
      nameRU: 'Йогурт',
      nameDE: 'Jogurt',
      groupId: 1,
    },
    {
      id: 5,
      nameEN: 'Cream',
      nameRU: 'Сливки',
      nameDE: 'Sahne',
      groupId: 1,
    },
    {
      id: 6,
      nameEN: 'Sour cream',
      nameRU: 'Сметана',
      nameDE: 'Saure Sahne',
      groupId: 1,
    },
    {
      id: 7,
      nameEN: 'Butter',
      nameRU: 'Масло',
      nameDE: 'Butter',
      groupId: 1,
    },
    {
      id: 8,
      nameEN: 'Curd',
      nameRU: 'Творог',
      nameDE: 'Quark',
      groupId: 1,
    },
    {
      id: 9,
      nameEN: 'Tomatoes',
      nameRU: 'Помидоры',
      nameDE: 'Tomaten',
      groupId: 2,
    },
    {
      id: 10,
      nameEN: 'Cucumber',
      nameRU: 'Огурец',
      nameDE: 'Gurken',
      groupId: 2,
    },
    {
      id: 11,
      nameEN: 'Potatoes',
      nameRU: 'Картофель',
      nameDE: 'Kartoffel',
      groupId: 2,
    },
    {
      id: 12,
      nameEN: 'Carrot',
      nameRU: 'Мокровь',
      nameDE: 'Möhre',
      groupId: 2,
    },
    {
      id: 13,
      nameEN: 'Beet',
      nameRU: 'Свекла',
      nameDE: 'Rote Bete',
      groupId: 2,
    },
    {
      id: 14,
      nameEN: 'Onion',
      nameRU: 'Лук',
      nameDE: 'Zwiebeln',
      groupId: 2,
    },
    {
      id: 15,
      nameEN: 'Garlic',
      nameRU: 'Чеснок',
      nameDE: 'Knoblauch',
      groupId: 2,
    },
    {
      id: 16,
      nameEN: 'Pepper',
      nameRU: 'Перец',
      nameDE: 'Paprika',
      groupId: 2,
    },
    {
      id: 17,
      nameEN: 'Cabbage',
      nameRU: 'Капуста',
      nameDE: 'Kohl',
      groupId: 2,
    },
    {
      id: 18,
      nameEN: 'Eggplant',
      nameRU: 'Баклажан',
      nameDE: 'Aubergine',
      groupId: 2,
    },
    {
      id: 19,
      nameEN: 'Apples',
      nameRU: 'Яблоки',
      nameDE: 'Äpfel',
      groupId: 3,
    },
    {
      id: 20,
      nameEN: 'Bananas',
      nameRU: 'Бананы',
      nameDE: 'Bananen',
      groupId: 3,
    },
    {
      id: 21,
      nameEN: 'Pear',
      nameRU: 'Груша',
      nameDE: 'Birne',
      groupId: 3,
    },
    {
      id: 22,
      nameEN: 'Tangerines',
      nameRU: 'Мандарины',
      nameDE: 'Mandarine',
      groupId: 3,
    },
    {
      id: 23,
      nameEN: 'Lemon',
      nameRU: 'Лимон',
      nameDE: 'Citrone',
      groupId: 3,
    },
    {
      id: 24,
      nameEN: 'Oranges',
      nameRU: 'Апельсины',
      nameDE: 'Orangen',
      groupId: 3,
    },
    {
      id: 25,
      nameEN: 'Grapefruits',
      nameRU: 'Грейпфрут',
      nameDE: 'Grapefruite',
      groupId: 3,
    },
    {
      id: 26,
      nameEN: 'Avocado',
      nameRU: 'Авокадо',
      nameDE: 'Avocado',
      groupId: 3,
    },
    {
      id: 27,
      nameEN: 'Kiwi',
      nameRU: 'Киви',
      nameDE: 'Kiwi',
      groupId: 3,
    },
    {
      id: 28,
      nameEN: 'Pineapple',
      nameRU: 'Ананас',
      nameDE: 'Ananas',
      groupId: 3,
    },
    {
      id: 29,
      nameEN: 'Strawberries',
      nameRU: 'Клубника',
      nameDE: 'Erdbeeren',
      groupId: 3,
    },
    {
      id: 30,
      nameEN: 'Raspberries',
      nameRU: 'Малина',
      nameDE: 'Himbeeren',
      groupId: 3,
    },
    {
      id: 31,
      nameEN: 'Bluberries',
      nameRU: 'Голубика',
      nameDE: 'Blaubeeren',
      groupId: 3,
    },
    {
      id: 32,
      nameEN: 'Grape',
      nameRU: 'Виноград',
      nameDE: 'Weintrauben',
      groupId: 3,
    },
    {
      id: 33,
      nameEN: 'Watermelon',
      nameRU: 'Арбуз',
      nameDE: 'Wassermelone',
      groupId: 3,
    },
    {
      id: 34,
      nameEN: 'Melon',
      nameRU: 'Дыня',
      nameDE: 'Hönigmelone',
      groupId: 3,
    },
    {
      id: 35,
      nameEN: 'Water',
      nameRU: 'Вода',
      nameDE: 'Wasser',
      groupId: 4,
    },
    {
      id: 36,
      nameEN: 'Wine',
      nameRU: 'Вино',
      nameDE: 'Wein',
      groupId: 4,
    },
    {
      id: 37,
      nameEN: 'Beer',
      nameRU: 'Пиво',
      nameDE: 'Bier',
      groupId: 4,
    },
    {
      id: 38,
      nameEN: 'Vodka',
      nameRU: 'Водка',
      nameDE: 'Schnaps',
      groupId: 4,
    },
    {
      id: 39,
      nameEN: 'Cognac',
      nameRU: 'Коньяк',
      nameDE: 'Cognac',
      groupId: 4,
    },
    {
      id: 40,
      nameEN: 'Rum',
      nameRU: 'Ром',
      nameDE: 'Rum',
      groupId: 4,
    },
    {
      id: 41,
      nameEN: 'Gin',
      nameRU: 'Джин',
      nameDE: 'Gin',
      groupId: 4,
    },
    {
      id: 42,
      nameEN: 'Whiskey',
      nameRU: 'Виски',
      nameDE: 'Whiskey',
      groupId: 4,
    },
    {
      id: 43,
      nameEN: 'Absinthe',
      nameRU: 'Абсент',
      nameDE: 'Absinth',
      groupId: 4,
    },
    {
      id: 44,
      nameEN: 'Champagne',
      nameRU: 'Шампанское',
      nameDE: 'Champagner',
      groupId: 4,
    },
    {
      id: 45,
      nameEN: 'Coca-Cola',
      nameRU: 'Кока-кола',
      nameDE: 'Coca-Cola',
      groupId: 4,
    },
    {
      id: 46,
      nameEN: 'Mineral water',
      nameRU: 'Минералка',
      nameDE: 'Mineralwasser',
      groupId: 4,
    },
    {
      id: 47,
      nameEN: 'Juice',
      nameRU: 'Сок',
      nameDE: 'Saft',
      groupId: 4,
    },
    {
      id: 48,
      nameEN: 'Tea',
      nameRU: 'Чай',
      nameDE: 'Tee',
      groupId: 4,
    },
    {
      id: 49,
      nameEN: 'Energy drink',
      nameRU: 'Энергетик',
      nameDE: 'Energydrink',
      groupId: 4,
    },
    {
      id: 50,
      nameEN: 'Pepsi-Cola',
      nameRU: 'Пепси-кола',
      nameDE: 'Pepsi-Cola',
      groupId: 4,
    },
    {
      id: 51,
      nameEN: 'Lemonade',
      nameRU: 'Лимонад',
      nameDE: 'Limonade',
      groupId: 4,
    },
    {
      id: 52,
      nameEN: 'Chicken',
      nameRU: 'Курица',
      nameDE: 'Huhn',
      groupId: 5,
    },
    {
      id: 53,
      nameEN: 'Pork',
      nameRU: 'Свинина',
      nameDE: 'Schwein',
      groupId: 5,
    },
    {
      id: 54,
      nameEN: 'Beef',
      nameRU: 'Говядина',
      nameDE: 'Rind',
      groupId: 5,
    },
    {
      id: 55,
      nameEN: 'Duck',
      nameRU: 'Утка',
      nameDE: 'Ente',
      groupId: 5,
    },
    {
      id: 56,
      nameEN: 'Turkey',
      nameRU: 'Индейка',
      nameDE: 'Pute',
      groupId: 5,
    },
    {
      id: 57,
      nameEN: 'Rabbit',
      nameRU: 'Кролик',
      nameDE: 'Kaninchen',
      groupId: 5,
    },
    {
      id: 58,
      nameEN: 'Minced meat',
      nameRU: 'Фарш',
      nameDE: 'Hackfleisch',
      groupId: 5,
    },
    {
      id: 59,
      nameEN: 'Black bread',
      nameRU: 'Черный хлеб',
      nameDE: 'Schwarzbrot',
      groupId: 6,
    },
    {
      id: 60,
      nameEN: 'White bread',
      nameRU: 'Белый хлеб',
      nameDE: 'Weißbrot',
      groupId: 6,
    },
    {
      id: 61,
      nameEN: 'Pie',
      nameRU: 'Пирог',
      nameDE: 'Kuchen',
      groupId: 6,
    },
    {
      id: 62,
      nameEN: 'Buns',
      nameRU: 'Булочки',
      nameDE: 'Brötchen',
      groupId: 6,
    },
    {
      id: 63,
      nameEN: 'Pasta',
      nameRU: 'Макароны',
      nameDE: 'Nudeln',
      groupId: 7,
    },
    {
      id: 64,
      nameEN: 'Spaghetti',
      nameRU: 'Спагетти',
      nameDE: 'Spaghetti',
      groupId: 7,
    },
    {
      id: 65,
      nameEN: 'Rice',
      nameRU: 'Рис',
      nameDE: 'Reis',
      groupId: 7,
    },
    {
      id: 66,
      nameEN: 'Oatmeal',
      nameRU: 'Овсянка',
      nameDE: 'Haferflocken',
      groupId: 7,
    },
    {
      id: 67,
      nameEN: 'Beans',
      nameRU: 'Бобы',
      nameDE: 'Bohnen',
      groupId: 7,
    },
    {
      id: 68,
      nameEN: 'Red fish',
      nameRU: 'Красная рыба',
      nameDE: 'Roter Fisch',
      groupId: 8,
    },
    {
      id: 69,
      nameEN: 'White fish',
      nameRU: 'Белая рыба',
      nameDE: 'Weißer Fisch',
      groupId: 8,
    },
    {
      id: 70,
      nameEN: 'Shrimp',
      nameRU: 'Креветки',
      nameDE: 'Garnelen',
      groupId: 8,
    },
    {
      id: 71,
      nameEN: 'Caviar',
      nameRU: 'Икра',
      nameDE: 'Kaviar',
      groupId: 8,
    },
    {
      id: 72,
      nameEN: 'Crab sticks',
      nameRU: 'Крабовые палочки',
      nameDE: 'Krabbenstangen',
      groupId: 8,
    },
    {
      id: 73,
      nameEN: 'Mussels',
      nameRU: 'Мидии',
      nameDE: 'Muscheln',
      groupId: 8,
    },
    {
      id: 74,
      nameEN: 'Squid',
      nameRU: 'Кальмары',
      nameDE: 'Tintenfisch',
      groupId: 8,
    },
    {
      id: 75,
      nameEN: 'Flour',
      nameRU: 'Мука',
      nameDE: 'Mehl',
      groupId: 9,
    },
    {
      id: 76,
      nameEN: 'Baking powder',
      nameRU: 'Разрыхлитель',
      nameDE: 'Backpulver',
      groupId: 9,
    },
    {
      id: 77,
      nameEN: 'Dough',
      nameRU: 'Тесто',
      nameDE: 'Teig',
      groupId: 9,
    },
    {
      id: 78,
      nameEN: 'Vanilin',
      nameRU: 'Ванилин',
      nameDE: 'Vanilin',
      groupId: 9,
    },
    {
      id: 79,
      nameEN: 'Yeast',
      nameRU: 'Дрожжи',
      nameDE: 'Hefe',
      groupId: 9,
    },
    {
      id: 80,
      nameEN: 'Sugar',
      nameRU: 'Сахар',
      nameDE: 'Zucker',
      groupId: 9,
    },
    {
      id: 81,
      nameEN: 'Salt',
      nameRU: 'Соль',
      nameDE: 'Salz',
      groupId: 9,
    },
    {
      id: 82,
      nameEN: 'Cinnamon',
      nameRU: 'Корица',
      nameDE: 'Zimt',
      groupId: 9,
    },
    {
      id: 83,
      nameEN: 'Coockies',
      nameRU: 'Печенье',
      nameDE: 'Kekse',
      groupId: 10,
    },
    {
      id: 84,
      nameEN: 'Sweets',
      nameRU: 'Конфеты',
      nameDE: 'Konfekt',
      groupId: 10,
    },
    {
      id: 85,
      nameEN: 'Cake',
      nameRU: 'Торт',
      nameDE: 'Torte',
      groupId: 10,
    },
    {
      id: 86,
      nameEN: 'Chocolate',
      nameRU: 'Шоколад',
      nameDE: 'Schokolade',
      groupId: 10,
    },
    {
      id: 87,
      nameEN: 'Marmalade',
      nameRU: 'Мармелад',
      nameDE: 'Marmelade',
      groupId: 10,
    },
    {
      id: 88,
      nameEN: 'Marshmallows',
      nameRU: 'Зефир',
      nameDE: 'Marshmallows',
      groupId: 10,
    },
    {
      id: 89,
      nameEN: 'Pizza',
      nameRU: 'Пицца',
      nameDE: 'Pizza',
      groupId: 11,
    },
    {
      id: 90,
      nameEN: 'Dumplings',
      nameRU: 'Пельмени',
      nameDE: 'Pelmeni',
      groupId: 11,
    },
    {
      id: 91,
      nameEN: 'Meatballs',
      nameRU: 'Котлеты',
      nameDE: 'Koteletts',
      groupId: 11,
    },
    {
      id: 92,
      nameEN: 'Nuggets',
      nameRU: 'Наггетсы',
      nameDE: 'Nuggets',
      groupId: 11,
    },
    {
      id: 93,
      nameEN: 'Ice cream',
      nameRU: 'Мороженое',
      nameDE: 'Eis',
      groupId: 11,
    },
    {
      id: 94,
      nameEN: 'Salt',
      nameRU: 'Соль',
      nameDE: 'Salz',
      groupId: 12,
    },
    {
      id: 95,
      nameEN: 'Pepper',
      nameRU: 'Перец',
      nameDE: 'Pfeffer',
      groupId: 12,
    },
    {
      id: 96,
      nameEN: 'Paprika',
      nameRU: 'Паприка',
      nameDE: 'Paprika',
      groupId: 12,
    },
    {
      id: 97,
      nameEN: 'Turmeric',
      nameRU: 'Куркума',
      nameDE: 'Kurkuma',
      groupId: 12,
    },
    {
      id: 98,
      nameEN: 'Mayonnaise',
      nameRU: 'Майонез',
      nameDE: 'Mayonnaise',
      groupId: 12,
    },
    {
      id: 99,
      nameEN: 'Ketchup',
      nameRU: 'Кетчуп',
      nameDE: 'Ketchup',
      groupId: 12,
    },
    {
      id: 100,
      nameEN: 'Soy sauce',
      nameRU: 'Соевый соус',
      nameDE: 'Sojasauce',
      groupId: 12,
    },
    {
      id: 101,
      nameEN: 'Mustard',
      nameRU: 'Горчица',
      nameDE: 'Senf',
      groupId: 12,
    },
    {
      id: 102,
      nameEN: 'Chips',
      nameRU: 'Чипсы',
      nameDE: 'Chips',
      groupId: 13,
    },
    {
      id: 103,
      nameEN: 'Dry bread',
      nameRU: 'Сухарики',
      nameDE: 'Trockenes Brot',
      groupId: 13,
    },
    {
      id: 104,
      nameEN: 'Nuts',
      nameRU: 'Орешки',
      nameDE: 'Nüsse',
      groupId: 13,
    },
    {
      id: 105,
      nameEN: 'Salted fish',
      nameRU: 'Соленая рыба',
      nameDE: 'Gesalzener Fisch',
      groupId: 13,
    },
    {
      id: 106,
      nameEN: 'Squid rings',
      nameRU: 'Кольца кальмара',
      nameDE: 'Tintenfischringe',
      groupId: 13,
    },
    {
      id: 107,
      nameEN: 'Peas',
      nameRU: 'Горошек',
      nameDE: 'Erbsen',
      groupId: 14,
    },
    {
      id: 108,
      nameEN: 'Beans',
      nameRU: 'Фасоль',
      nameDE: 'Bohnen',
      groupId: 14,
    },
    {
      id: 109,
      nameEN: 'Corn',
      nameRU: 'Кукуруза',
      nameDE: 'Mais',
      groupId: 14,
    },
    {
      id: 110,
      nameEN: 'Olives',
      nameRU: 'Оливки',
      nameDE: 'Oliven',
      groupId: 14,
    },
    {
      id: 111,
      nameEN: 'Pineapple',
      nameRU: 'Ананас',
      nameDE: 'Ananas',
      groupId: 14,
    },
    {
      id: 112,
      nameEN: 'Peaches',
      nameRU: 'Персики',
      nameDE: 'Pfirsiche',
      groupId: 14,
    },
    {
      id: 113,
      nameEN: 'Cucumbers',
      nameRU: 'Огурцы',
      nameDE: 'Gurken',
      groupId: 14,
    },
    {
      id: 114,
      nameEN: 'Jam',
      nameRU: 'Варенье',
      nameDE: 'Marmelade',
      groupId: 14,
    },
  ],
  categories: [
    {
      id: 1,
      nameEN: 'Dairy & Eggs',
      nameRU: 'Молочные продукты & Яйца',
      nameDE: 'Milchprodukte & Eier',
      icon: 'fa-solid fa-egg'
    },
    {
      id: 2,
      nameEN: 'Vegetables',
      nameRU: 'Овощи',
      nameDE: 'Gemüse',
      icon: 'fa-solid fa-carrot'
    },
    {
      id: 3,
      nameEN: 'Fruits & Berries',
      nameRU: 'Фрукты & Ягоды',
      nameDE: 'Obst & Beeren',
      icon: 'fa-solid fa-apple-whole'
    },
    {
      id: 4,
      nameEN: 'Beverages',
      nameRU: 'Напитки',
      nameDE: 'Getränke',
      icon: 'fa-solid fa-martini-glass-citrus'
    },
    {
      id: 5,
      nameEN: 'Meat',
      nameRU: 'Мясо',
      nameDE: 'Fleisch',
      icon: 'fa-solid fa-burger'
    },
    {
      id: 6,
      nameEN: 'Bread & Bakery',
      nameRU: 'Хлеб & Выпечка',
      nameDE: 'Brot & Bäkerei',
      icon: 'fa-solid fa-bread-slice'
    },
    {
      id: 7,
      nameEN: 'Pasta & Cereal',
      nameRU: 'Макароны & Крупы',
      nameDE: 'Teigwaren & Grütze',
      icon: 'fa-solid fa-bowl-rice'
    },
    {
      id: 8,
      nameEN: 'Fish & Seafood',
      nameRU: 'Рыба & Морепродукты',
      nameDE: 'Fisch & Meeresfrüchte',
      icon: 'fa-solid fa-shrimp'
    },
    {
      id: 9,
      nameEN: 'Baking',
      nameRU: 'Выпечка',
      nameDE: 'Backen',
      icon: 'fa-solid fa-cookie-bite'
    },
    {
      id: 10,
      nameEN: 'Sweets',
      nameRU: 'Сладости',
      nameDE: 'Süssigkeiten',
      icon: 'fa-solid fa-cake-candles'
    },
    {
      id: 11,
      nameEN: 'Frozen foods',
      nameRU: 'Заморозка',
      nameDE: 'Gefrorenes Essen',
      icon: 'fa-solid fa-snowflake'
    },
    {
      id: 12,
      nameEN: 'Condiments & Spices',
      nameRU: 'Соусы & Специи',
      nameDE: 'Gewürze',
      icon: 'fa-solid fa-pepper-hot'
    },
    {
      id: 13,
      nameEN: 'Snacks',
      nameRU: 'Снеки',
      nameDE: 'Snacks',
      icon: 'fa-solid fa-people-pulling'
    },
    {
      id: 14,
      nameEN: 'Canned goods',
      nameRU: 'Консервы',
      nameDE: 'Konserve',
      icon: 'fa-solid fa-jar'
    }
  ]
});

const getters = {
  productsByGroupId: (state: State) => (groupId: string | number) => {
    return state.all.filter((item: Product) => item.groupId === groupId);
  },
  checkedProductsByGroupId: (state: State) => (groupId: string | number) => {
    return state.all.filter((item: Product) => item.groupId === groupId && item.inBasket);
  },
  checkedCategories: (state: State) => {
    return state.categories.filter((category: Category) => category.hasChecked);
  }
};

const mutations = {
  setInBasket: (state: State, payload: { id: string | number, inBasket: boolean }) => {
    const item = state.all.find((item: Product) => payload.id === item.id);
    const category = state.categories.find((category: Category) => category.id === item!.groupId);
    item!.inBasket = payload.inBasket;
    if (payload.inBasket) { category!.hasChecked = true; }
    else {
      const hasChecked = state.all.filter((item: Product) => item.groupId === category?.id)
        .some((item: Product) => item.inBasket);
      category!.hasChecked = hasChecked;
    }
  }
};

export default {
  namespaced: true,
  state,
  getters,
  mutations
};
